fixed chandler and changelog-generator

diff --git a/scripts/changelog-generator b/scripts/changelog-generator
--- a/scripts/changelog-generator
+++ b/scripts/changelog-generator
@@ -5,11 +5,11 @@ cd "$(dirname "$0")/.."
 APP_NAME=$(node -e 'console.log(require("./package.json").name)')
 
 echo "===> Running changelog generator..."
-
 . ./.env
 
 if ! [ -x "$(command -v github_changelog_generator)" ]; then
-  ./scripts/install/changelog-generator
+  echo 'Error: github_changelog_generator is not installed' >&2
+  exit 1
 fi
 
-github_changelog_generator -u generator -p ${APP_NAME} --enhancement-labels 'enhancement,Enhancement,features,Features,feature' --exclude-labels 'duplicate,question,invalid,wontfix,ignore,changelog ignore' --base CHANGELOG.md
+github_changelog_generator -u pedroarapua -p ${APP_NAME} --enhancement-labels 'enhancement,Enhancement,features,Features,feature' --exclude-labels 'duplicate,question,invalid,wontfix,ignore,changelog ignore' --base CHANGELOG.md
diff --git a/scripts/install/chandler b/scripts/install/chandler
--- a/scripts/install/chandler
+++ b/scripts/install/chandler
@@ -5,7 +5,8 @@ cd "$(dirname "$0")/../.."
 echo "===> Installing chandler..."
 
 if ! [ -x "$(command -v gem)" ]; then
-  ./scripts/install/ruby    
+  echo 'Error: gem is not installed'
+  exit 1
 fi
 
 sudo gem install chandler
