fixes sonar

diff --git a/scripts/chandler b/scripts/chandler
--- a/scripts/chandler
+++ b/scripts/chandler
@@ -7,4 +7,9 @@ APP_VERSION=$(node -e 'console.log(require("./package.json").version)')
 
 echo "===> Running Chandler..."
 
+if ! [ -x "$(command -v chandler)" ]; then
+  echo 'Error: chandler is not installed'
+  exit 1
+fi
+
 chandler push v${APP_VERSION}
diff --git a/scripts/sonar b/scripts/sonar
--- a/scripts/sonar
+++ b/scripts/sonar
@@ -7,7 +7,12 @@ APP_NAME=$(node -e 'console.log(require("./package.json").name)')
 
 echo "===> Running Sonar..."
 
-sonar-scanner \
+if ! [ -x "$(command -v sonar-scanner)" ]; then
+  echo 'Error: sonar-scanner is not installed'
+  exit 1
+fi
+
+~/sonar-scanner/bin/sonar-scanner \
   -Dsonar.projectKey=${SONAR_APP_NAME:-${APP_NAME}} \
   -Dsonar.organization=${ORGANIZATION_NAME:-pedroarapua-github} \
   -Dsonar.sources=src \
